version: '3.7'

services:
  minio:
    container_name: minio
    image: minio/minio
    volumes:
      - ./data1:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ZJbLwSLkT70mKEwj
      MINIO_ROOT_PASSWORD: J6GffHhTCrm0jeW0ZQymTYZLR8LZ7w1N
    command: minio server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3